# Generated by Django 4.1.1 on 2023-09-25 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecomerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Punjab', 'Punjab'), ('West Bengal', 'West Bengal'), ('Gujrat', 'Gujrat'), ('Sikkim', 'Sikkim'), ('Odisa', 'Odisa'), ('Kerala', 'Kerala'), ('Tamil Nadu', 'Tamil Nadu'), ('Assam', 'Assam'), ('Goa', 'Goa'), ('Delhi', 'Delhi')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
